#Large Crystal properties file
#Tue Jun 09 01:53:19 CEST 2026
shouldGenerateEchoCrystal=true
shouldGenerateGlowstoneCrystal=true
shouldGeneratePrismarineCrystal=true
shouldGenerateQuartzCrystal=true
shouldGenerateWrappistCrystal=true
