#Large Crystal properties file
#Wed May 27 02:40:43 UTC 2026
shouldGenerateEchoCrystal=true
shouldGenerateGlowstoneCrystal=true
shouldGeneratePrismarineCrystal=true
shouldGenerateQuartzCrystal=true
shouldGenerateWrappistCrystal=true
