#Large Crystal properties file
#Wed May 27 07:28:43 UTC 2026
shouldGenerateEchoCrystal=true
shouldGenerateGlowstoneCrystal=true
shouldGeneratePrismarineCrystal=true
shouldGenerateQuartzCrystal=true
shouldGenerateWrappistCrystal=true
