#Overworld Geodes properties file
#Tue Jun 09 01:53:19 CEST 2026
shouldGenerateCelestiteGeodes=true
shouldGenerateDiamondGeodes=true
shouldGenerateEchoGeodes=true
shouldGenerateEmeraldGeodes=true
shouldGenerateLapisGeodes=true
shouldGeneratePinkTopazGeodes=true
shouldGeneratePrismarineGeodes=true
shouldGenerateRedstoneGeodes=true
